Create database QL_CAPHE
Go
Use QL_CAPHE
Go
--Generate SQL - Copied
CREATE TABLE ChucVu
(
  MaCV VARCHAR(10) NOT NULL,
  TenCV NVARCHAR(70) DEFAULT 'Unknown',
  PRIMARY KEY (MaCV)
);

CREATE TABLE Ban
(
  MaBan VARCHAR(10) NOT NULL,
  TrangThai BIT DEFAULT 1,
  PRIMARY KEY (MaBan)
);

CREATE TABLE KhachHang
(
  MaKH VARCHAR(10) NOT NULL,
  HoTen NVARCHAR(70) NOT NULL,
  SDT VARCHAR(10) DEFAULT '00000000000',
  NgaySinh DATE DEFAULT '1900-01-01',
  DiemTichLuy INT DEFAULT 0,
  XepHang NVARCHAR(10) DEFAULT N'Đồng',
  PRIMARY KEY (MaKH)
);

CREATE TABLE NhaCungCap
(
  MaNCC INT NOT NULL IDENTITY(1,1),
  TenNCC NVARCHAR(70) DEFAULT 'Unknown',
  PRIMARY KEY (MaNCC)
);

CREATE TABLE PhanLoai
(
  MaLoai VARCHAR(10) NOT NULL,
  TenLoai NVARCHAR(70) DEFAULT 'Unknown',
  PRIMARY KEY (MaLoai)
);

CREATE TABLE Kho_Nguyen_Lieu
(
  MaNL VARCHAR(10) NOT NULL,
  TenNL NVARCHAR(70) DEFAULT 'Unknown',
  SLTonKho INT DEFAULT 0,
  DonViTinh NVARCHAR(10) DEFAULT 'Unknown',
  PRIMARY KEY (MaNL)
);

CREATE TABLE KhuyenMai
(
  MaKM VARCHAR(10) NOT NULL,
  TenKM NVARCHAR(70) DEFAULT 'Unknown',
  NgayBD DATE ,
  NgayKT DATE,
  TiLe FLOAT DEFAULT 0,
  PRIMARY KEY (MaKM)
);

CREATE TABLE LoaiSuCo
(
  MaLoai INT NOT NULL IDENTITY(1,1),
  TenLoai NVARCHAR(70) DEFAULT 'Unknown',
  PRIMARY KEY (MaLoai)
);

CREATE TABLE ThucDon
(
  MaMon VARCHAR(10) NOT NULL,
  TenMon NVARCHAR(70) DEFAULT 'Unknown',
  Size VARCHAR(1) DEFAULT 'M',
  Gia MONEY DEFAULT 0,
  MaLoai VARCHAR(10) NOT NULL,
  PRIMARY KEY (MaMon),
  FOREIGN KEY (MaLoai) REFERENCES PhanLoai(MaLoai)
);

CREATE TABLE NhanVien
(
  MaNV VARCHAR(10) NOT NULL,
  HoTen NVARCHAR(70) DEFAULT 'Unknown',
  NgaySinh DATE ,
  SDT VARCHAR(10) DEFAULT '0000000000',
  CMND VARCHAR(12) DEFAULT '000000000000',
  MaCV VARCHAR(10) NOT NULL,
  GioiTinh NVARCHAR(10) DEFAULT N'Nam',
  PRIMARY KEY (MaNV),
  FOREIGN KEY (MaCV) REFERENCES ChucVu(MaCV)
);

CREATE TABLE PhieuNhap
(
  MaPN INT NOT NULL  IDENTITY(1,1),
  NgayNhap DATE DEFAULT GETDATE(),
  MaNV VARCHAR(10) NOT NULL,
  PRIMARY KEY (MaPN),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE PhieuXuat
(
  MaPX INT NOT NULL  IDENTITY(1,1),
  NgayXuat DATE,
  MaNV VARCHAR(10) NOT NULL,
  PRIMARY KEY (MaPX),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CTPhieuNhap
(
  SoLuong INT NOT NULL,
  MaPN INT NOT NULL,
  MaNL VARCHAR(10) NOT NULL,
  MaNCC INT NOT NULL,
  PRIMARY KEY (MaPN, MaNL),
  FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN),
  FOREIGN KEY (MaNL) REFERENCES Kho_Nguyen_Lieu(MaNL),
  FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

CREATE TABLE CTPhieuXuat
(
  SoLuong INT DEFAULT 0,
  MaPX INT NOT NULL,
  MaNL VARCHAR(10) NOT NULL,
  PRIMARY KEY (MaPX, MaNL),
  FOREIGN KEY (MaPX) REFERENCES PhieuXuat(MaPX),
  FOREIGN KEY (MaNL) REFERENCES Kho_Nguyen_Lieu(MaNL)
);

CREATE TABLE SuCo
(
  MaSC INT  NOT NULL IDENTITY(1,1),
  TenSC NVARCHAR(70) DEFAULT 'Unknown',
  MotaCT NVARCHAR(2000) DEFAULT 'Unknown',
  HinhThuc NVARCHAR(20) DEFAULT 'Unknown',
  ChiPhi MONEY DEFAULT 0,
  TGXayRa DATE,
  TGKetThuc DATE,
  NguoiLap VARCHAR(10) ,
  MaLoai INT NOT NULL,
  PRIMARY KEY (MaSC),
  FOREIGN KEY (NguoiLap) REFERENCES NhanVien(MaNV),
  FOREIGN KEY (MaLoai) REFERENCES LoaiSuCo(MaLoai)
);

CREATE TABLE TaiKhoan
(
  TenDN VARCHAR(30) NOT NULL,
  MatKhau VARCHAR(20) NOT NULL,
  NgayTao DATE DEFAULT GETDATE(),
  MaNV VARCHAR(10) NOT NULL,
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE Phieu_Nhap_tam_thoi
(
  MaPNTT INT NOT NULL IDENTITY(1,1),
  NgayNhap DATE DEFAULT GETDATE(),
  MaNCC INT NOT NULL,
  MaPN INT NOT NULL,
  PRIMARY KEY (MaPNTT),
  FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
  FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN)
);

CREATE TABLE Phieu_Xuat_tam_thoi
(
  MaPXTT INT NOT NULL IDENTITY(1,1),
  NgayXuat DATE DEFAULT GETDATE(),
  MaPX INT NOT NULL,
  PRIMARY KEY (MaPXTT),
  FOREIGN KEY (MaPX) REFERENCES PhieuXuat(MaPX)
);

CREATE TABLE CTPX_tam_thoi
(
  SoLuong INT DEFAULT 0,
  MaNL VARCHAR(10) NOT NULL,
  MaPXTT INT NOT NULL,
  MaNCC INT NOT NULL,
  PRIMARY KEY (MaNL, MaPXTT),
  FOREIGN KEY (MaNL) REFERENCES Kho_Nguyen_Lieu(MaNL),
  FOREIGN KEY (MaPXTT) REFERENCES Phieu_Xuat_tam_thoi(MaPXTT),
  FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);



CREATE TABLE HoaDon
(
  MaHD INT NOT NULL IDENTITY(1,1),
  NgayLap DATE DEFAULT GETDATE(),
  KhachTra INT DEFAULT 0,
  GhiChu VARCHAR(10) DEFAULT 'Unknown',
  MaBan VARCHAR(10) NOT NULL,
  MaNV VARCHAR(10) NOT NULL,
  MaKH VARCHAR(10) NOT NULL,
  PRIMARY KEY (MaHD),
  FOREIGN KEY (MaBan) REFERENCES Ban(MaBan),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
  FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE CTHoaDon
(
  SoLuong INT DEFAULT 0,
  TriGia MONEY DEFAULT 0,
  MaHD INT NOT NULL,
  MaMon VARCHAR(10) NOT NULL,
  PRIMARY KEY (MaHD, MaMon),
  FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
  FOREIGN KEY (MaMon) REFERENCES ThucDon(MaMon)
);

CREATE TABLE CTKhuyenMai
(
  MaKM VARCHAR(10) NOT NULL,
  MaHD INT NOT NULL,
  PRIMARY KEY (MaKM, MaHD),
  FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM),
  FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
);
