/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ExcuteData;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author HieuThao
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        setLocationRelativeTo (null);
        trongsuot();
    }
    ExcuteData ex;
    public TrangChu(ExcuteData ex) {
        initComponents();
        setLocationRelativeTo (null);
        trongsuot();
        this.ex = ex;
    }
    private void trongsuot()
    {
        btn_goimon.setOpaque(false);
        btn_goimon.setContentAreaFilled(false);
        btn_goimon.setBorderPainted(false);
        btn_goimon.setForeground(Color.WHITE); // Đặt màu chữ trắng cho button (tuỳ chọn)
        
        // Đặt màu nền trong suốt cho button
        btn_goimon.setBackground(new Color(0, 0, 0, 0));
        
        btn_nhap.setOpaque(false);
        btn_nhap.setContentAreaFilled(false);
        btn_nhap.setBorderPainted(false);
        btn_nhap.setForeground(Color.WHITE); // Đặt màu chữ trắng cho button (tuỳ chọn)
        
        // Đặt màu nền trong suốt cho button
        btn_nhap.setBackground(new Color(0, 0, 0, 0));
        
        btn_suco.setOpaque(false);
        btn_suco.setContentAreaFilled(false);
        btn_suco.setBorderPainted(false);
        btn_suco.setForeground(Color.WHITE); // Đặt màu chữ trắng cho button (tuỳ chọn)
        
        // Đặt màu nền trong suốt cho button
        btn_suco.setBackground(new Color(0, 0, 0, 0));
        
        btn_xuat.setOpaque(false);
        btn_xuat.setContentAreaFilled(false);
        btn_xuat.setBorderPainted(false);
        btn_xuat.setForeground(Color.WHITE); // Đặt màu chữ trắng cho button (tuỳ chọn)
        
        // Đặt màu nền trong suốt cho button
        btn_xuat.setBackground(new Color(0, 0, 0, 0));
        
        btn_thoat.setOpaque(false);
        btn_thoat.setContentAreaFilled(false);
        btn_thoat.setBorderPainted(false);
        btn_thoat.setForeground(Color.WHITE); // Đặt màu chữ trắng cho button (tuỳ chọn)
        
        // Đặt màu nền trong suốt cho button
        btn_thoat.setBackground(new Color(0, 0, 0, 0));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_goimon = new javax.swing.JButton();
        btn_xuat = new javax.swing.JButton();
        btn_nhap = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        btn_suco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setMinimumSize(new java.awt.Dimension(780, 600));
        main.setOpaque(false);
        main.setLayout(new java.awt.BorderLayout());
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 600));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(220, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 600));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_goimon.setBackground(new java.awt.Color(242, 242, 242));
        btn_goimon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_goimon.setText("GỌI MÓN");
        btn_goimon.setAlignmentY(0.0F);
        btn_goimon.setBorder(null);
        btn_goimon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(btn_goimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        btn_xuat.setBackground(new java.awt.Color(242, 242, 242));
        btn_xuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_xuat.setText("XỬ LÝ XUẤT");
        btn_xuat.setAlignmentY(0.0F);
        btn_xuat.setBorder(null);
        btn_xuat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(btn_xuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 70));

        btn_nhap.setBackground(new java.awt.Color(242, 242, 242));
        btn_nhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_nhap.setText("XỬ LÝ NHẬP");
        btn_nhap.setAlignmentY(0.0F);
        btn_nhap.setBorder(null);
        btn_nhap.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(btn_nhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 220, 70));

        btn_thoat.setBackground(new java.awt.Color(242, 242, 242));
        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_thoat.setText("ĐĂNG XUẤT");
        btn_thoat.setAlignmentY(0.0F);
        btn_thoat.setBorder(null);
        btn_thoat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 220, 70));

        btn_suco.setBackground(new java.awt.Color(242, 242, 242));
        btn_suco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_suco.setText("SỰ CỐ");
        btn_suco.setAlignmentY(0.0F);
        btn_suco.setBorder(null);
        btn_suco.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_suco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sucoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_suco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hinh-ca-phe-mot-minh-dep-buon-nhat.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void doimaubtn(JButton t)
    {
        t.setOpaque(true);
        t.setContentAreaFilled(true);
        t.setBorderPainted(false);
        t.setForeground(Color.BLACK); // Đặt màu chữ trắng cho button (tuỳ chọn)
        
        // Đặt màu nền trong suốt cho button
        t.setBackground(new Color(255, 255, 255));
    }
    private void btn_sucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sucoActionPerformed
        // TODO add your handling code here:
        doimaubtn(btn_suco);
        main.add(new PhieuSuCo());
        setForm(new XuLySuCo(main, ex));
        
    }//GEN-LAST:event_btn_sucoActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login t = new Login(ex);
        t.showLogin();
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void setForm(JComponent com) {
        main.removeAll();
        com.setVisible(true);
        main.add(com);
        main.repaint();
        main.revalidate();
        SwingUtilities.getWindowAncestor(main).setVisible(true);
    }
   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goimon;
    private javax.swing.JButton btn_nhap;
    private javax.swing.JButton btn_suco;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
